---
title: "exploratory_analysis_cleanin_TanvirK"
author: "Tanvir Khan" 
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Before Recoding
```{r}
merged_data_clean <- 
  merged_data %>%
  select(-multyear, -ancestr1, -ancestr2, -occ, -ind, -incwage, -incwelfr, -poverty, -occscore, -pwpuma00)
```


# Recoding Race and changing it to a factor variable 
```{r}
merged_data_clean <-
  merged_data %>%
  janitor::clean_names() %>%
  mutate(race = recode(race, 
                    "1" = "White",
                    "2" = "Black/African America",
                    "3" = "American Indian or Alaska Native",
                    "4" = "Chinese",
                    "5" = "Japanese",
                    "6" = "Other Asian or Pacific Islander",
                    "7" = "Other race, nec",
                    "8" = "Two major races", 
                    "9" = "Three or more major races")) %>%
  mutate(race = as.factor(race)) %>% 
  mutate(sex = recode(sex,
                       "1" = "Male",
                       "2" = "Female")) %>%
  mutate(sex = as.factor(sex)) %>%
  mutate(hispan = recode(hispan,
                        "0" = "Not Hispanic", 
                        "1" = "Mexican",
                        "2" = "Puerto Rican",
                        "3" = "Cuban",
                        "4" = "Other",
                        "9" = "Not Reported")) %>%
  mutate(hispan = as.factor(hispan)) %>% 
  mutate(foodstmp = recode(foodstmp,
                          "0" = "N/A",
                          "1" = "No",
                          "2" = "Yes")) %>%
  mutate(foodstmp = as.factor(foodstmp)) %>% 
  mutate(citizen = recode(citizen,
                          "0" = "N/A",
                          "1" = "Born abroad of American parents",
                          "2" = "Naturalized citizen",
                          "3" = "Not a citizen",
                          "4" = "Not a citizen, but has received first papers",
                          "5" = "Foreign born, citizenship status not reported",
                          "8" = "Illegible",
                          "9" = "Missing/blank")) %>%
  mutate(citizen = as.factor(citizen)) %>% 
  mutate(hcovany = recode(hcovany,
                               "1" = "No health insurance coverage",
                               "2" = "With health insurance coverage")) %>%
  mutate(hcovany = as.factor(hcovany)) %>% 
  mutate(hcovpriv = recode(hcovpriv,
                          "1" = "Without private health insurance coverage",
                          "2" = "With private health insurance coverage")) %>% 
  mutate(hcovpriv = as.factor(hcovpriv)) %>% 
  mutate(hcovpub = recode(hcovpub,
                          "1" = "Without public health insurance coverage",
                          "2" = "With public health insurance coverage")) %>% 
  mutate(hcovpub = as.factor(hcovpub)) %>% 
  mutate(educ = recode(educ,
                       "00" =	"N/A or no schooling",
                       "01" =	"Nursery school to grade 4",
                       "02" = "Grade 5, 6, 7, or 8",
                       "03" = "Grade 9",
                       "04" = "Grade 10",
                       "05" =	"Grade 11",
                       "06"	= "Grade 12",
                       "07" = "1 year of college",
                       "08" =	"2 years of college", 
                       "09" =	"3 years of college",
                       "10"	= "4 years of college", 
                       "11" =	"5+ years of college")) %>% 
  mutate(empstat = recode(empstat,
                          "0" = "N/A",
                          "1" = "Employed",
                          "2" = "Unemployed",
                          "3" = "Not in labor force")) %>%
  mutate(empstat = as.factor(empstat)) %>% 
  mutate(labforce = recode(labforce,
                           "0" = "N/A",
                           "1" = "No, not in the labor force",
                           "2" = "Yes, in the labor force")) %>%
  mutate(labforce = as.factor(labforce))
```


