---
title: "P8105: Data Science I"
author: "Cleaning Playground<br>Zachary Katz (UNI: zak2132)"
output:
  github_document:
    toc: TRUE
---

<!------------------------------------------------------------------------------
Preamble
------------------------------------------------------------------------------->

```{r, echo = FALSE, message = FALSE, warning = FALSE}
# load necessary packages
library(tidyverse)

# set knitr defaults
knitr::opts_chunk$set(
    echo      = TRUE
  , message   = FALSE
  , fig.width = 6
  , fig.asp   = .6
  , out.width = "90%"
)

# set theme defaults
theme_set(
  theme_bw() +
  theme(
    legend.position = "bottom"
    , plot.title    = element_text(hjust = 0.5)
    , plot.subtitle = element_text(hjust = 0.5)    
    , plot.caption  = element_text(hjust = 0.0)
  )
)

# set color scale defaults
options(
    ggplot2.continuous.colour = "viridis"
  , ggplot2.continuous.fill   = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete   = scale_fill_viridis_d
```

<!------------------------------------------------------------------------------
Overview
------------------------------------------------------------------------------->

# Unzipping the Census Data

```{r}
jimzip <- function(csv_file, path) {
  # create full path to csv file
  full_csv <- paste0(path, "/", csv_file)
  # append ".zip" to csv file
  zip_file <- paste0(full_csv, ".zip")
  # unzip file
  unzip(zip_file)
  # read csv
  data_extract <- read_csv(csv_file)
  # be sure to remove file once unzipped (it will live in working directory)
  on.exit(file.remove(csv_file))
  # output data
  data_extract
}

census_data <- jimzip("census_filtered.csv", "./data")
head(census_data) %>%  knitr::kable()
```

# Merging the Outcome Data

```{r}
health_data <-
  read_csv("./data/outcome_puma.csv") %>%
  rename(puma = puma10)

merged_data <- merge(census_data, health_data, by = "puma")
rm(census_data)

head(merged_data) %>% knitr::kable()
```

# Cleaning the Outcome Data

```{r}
# Cleaning the merged data frame
cleaned_data = 
  merged_data %>% 
  # Eliminate duplicate rows
  distinct() %>% 
  # Rename variables
  rename(
    borough = countyfip,
    has_broadband = cihispeed,
    birthplace = bpl,
    years_in_usa = yrsusa1,
    education = educ,
    employment = empstat,
    personal_income = inctot,
    family_income = ftotinc,
    work_transport = tranwork,
    household_income = hhincome,
    on_foodstamps = foodstmp,
    family_size = famsize,
    num_children = nchild,
    US_citizen = citizen,
    puma_vacc_rate = puma_vacc_per
  ) %>% 
  # Recode variables using IPUMS dictionary
  mutate(
    borough = recode(
      borough,
      "5" = "Bronx",
      "47" = "Brooklyn",
      "61" = "Manhattan",
      "81" = "Queens",
      "85" = "Staten Island"
    ),
    on_foodstamps = recode(
      on_foodstamps,
      "1" = "No",
      "2" = "Yes"
    ),
    has_broadband = case_when(
      has_broadband == "20" ~ "No",
      has_broadband != "20" ~ "Yes"
    ),
    sex = recode(
      sex,
      "1" = "Male",
      "2" = "Female"
    ),
    race = case_when(
      race == "1" ~ "White",
      race == "2" ~ "Black",
      race == "3" ~ "American Indian",
      race %in% c(4,5,6) ~ "Asian",
      race == "7" ~ "Other",
      race %in% c(8,9) ~ "2+ races"
    ),
    hispan = case_when(
      hispan == "0" ~ "No",
      hispan %in% c(1,2,3,4) ~ "Yes",
      hispan == "9" ~ "Not Reported"
    ),
    birthplace = case_when(
      birthplace %in% 1:120 ~"US",
      birthplace %in% 121:950 ~ "Non-US",
      birthplace == 999 ~"Unknown"
    ),
    US_citizen = case_when(
      US_citizen %in% c(1,2) ~ "Yes",
      US_citizen %in% 3:8 ~"No",
      US_citizen %in% c(0,9) ~ "Unknown"
    ),
    language = case_when(
      language == "1" ~ "English",
      language == "12" ~ "Spanish",
      language == "43" ~ "Chinese",
      language == "0" ~ "Unknown",
      language == "31" ~ "Hindi",
      !language %in% c(1,12,43,0,31) ~ "Other"
    ),
    education = case_when(
      education %in% 1:6 ~ "No College",
      education %in% 7:11 ~ "College",
      education == 0 ~ "Unknown"
    ),
    health_insurance = case_when(
      hcovany == 1 ~ "None",
      hcovany == 2 && hcovpriv == 2 ~ "Private",
      hcovany == 2 && hcovpriv == 1 ~ "Public"
    ),
    employment = case_when(
      employment %in% c(0,3) ~ "Not in labor force",
      employment == 1 ~ "Employed",
      employment == 2 ~ "Unemployed"
    ),
    on_welfare = case_when(
      incwelfr > 0 ~ "Yes",
      incwelfr == 0 ~ "No"
    ),
    poverty_threshold = case_when(
      poverty > 100 ~ "Above",
      poverty < 100 ~ "Below"
    ),
    work_transport = case_when(
      work_transport %in% c(31:37, 39) ~ "Public Transit",
      work_transport %in% c(10:20, 38) ~ "Private Vehicle",
      work_transport == 50 ~ "Bicycle",
      work_transport == 60 ~ "Walking",
      work_transport == 80 ~ "Worked From Home",
      work_transport %in% c(0, 70) ~ "Other"
    ),
    rent = ifelse(
      rent == 9999, 0,
      rent
    ),
    household_income = ifelse(
      household_income %in% c(9999998,9999999), NA,
      household_income
    ),
    personal_income = ifelse(
      personal_income %in% c(9999998,9999999), NA,
      personal_income
    ),
    family_income = ifelse(
      family_income %in% c(9999998,9999999), NA,
      family_income
    )
  ) %>% 
  # Eliminate unnecessary variables
  select(-multyear, -hispan, -ancestr1, -ancestr2, -hcovany, -hcovpriv, -hcovpub, -labforce, -occ, -ind, -incwage, -incwelfr, -poverty, -occscore, -pwpuma00) %>% 
  # Reorder columns
  relocate(health_insurance, .before = personal_income) %>% 
  relocate(on_welfare, .before = work_transport) %>% 
  relocate(poverty_threshold, .before = work_transport) %>% 
  relocate(perwt, .before = cluster) %>% 
  # Factorize a number of variables for ease of future analysis
  mutate(
    puma = as.factor(puma),
    borough = as.factor(borough),
    on_foodstamps = as.factor(on_foodstamps),
    has_broadband = as.factor(has_broadband),
    sex = as.factor(sex),
    race = as.factor(race),
    birthplace = as.factor(birthplace),
    US_citizen = as.factor(US_citizen),
    language = as.factor(language),
    education = as.factor(education),
    employment = as.factor(employment),
    health_insurance = as.factor(health_insurance),
    on_welfare = as.factor(on_welfare),
    poverty_threshold = as.factor(poverty_threshold),
    work_transport = as.factor(work_transport)
  )

cleaned_data %>% View()
```

```{r}
### CHECK THIS OUT LATER
# Load survey package
library(survey)

# Use stratified cluster sampling design
survey_design = svydesign(
  ids = ~puma,
  weights = ~hhwt,
  strata = ~strata,
  data = cleaned_data
  )
```

```{r}

```

