---
title: "Linear Regression"
author: "Hun"
date: "12/5/2021"
output: html_document
---

# Modeling
```{r, echo = FALSE, message = FALSE, warning = FALSE}
library(tidyverse)
library(spatstat)
library(glmnet)
library(workflows)
library(dials)
library(janitor)
library(rstatix)
library(egg)
library(modelr)
library(PerformanceAnalytics)
library(robmed)
library(tidymodels)
library(lmtest)
library(sandwich)
library(performance)
library(olsrr)
```

```{r}

nyc_hh_summary <- read_csv("./modeling/data_for_regression.csv")

outcome_by_year <- 
  read_csv("./modeling/outcome_puma_by_year.csv") %>%
  rename(puma = puma10)

unbiased_data <- read_csv("./modeling/unbiased_group_means.csv") %>%
  merge(outcome_by_year, by = "puma")
```


## Correlation between predictors and 2020 hospitalizaiton rate (outcome variable)
```{r}
unbiased_data %>% 
  select(-puma_death_rate_2020, -puma_hosp_rate_2021, 
         -puma_death_rate_2021, -puma_vacc_per,
         -puma, -group_pop) %>%
  cor_mat() %>%
  cor_gather() %>%
  filter(var1 %in% "puma_hosp_rate_2020") %>%
  filter(!var2 %in% "puma_hosp_rate_2020") %>%
  mutate(
    sig_p = ifelse(p < 0.01, T, F),
    cor_if_sig = ifelse(p < 0.01, cor, NA)
    ) %>% 
  ggplot(aes(
    x = var1, 
    y = var2, 
    fill = cor,
    label = round(cor_if_sig, 2))) + 
  geom_tile(color = "white") +   
  geom_text(
    color = "white",
    size = 4
  ) + 
  scale_x_discrete(
    labels = c("Birth Weight")
  ) + 
  labs(
    x = "Outcome Variable",
    y = "Predictor Variables",
    title = "Correlation Matrix between Predictors and Outcome",
    subtitle = "significant predictors at significance level 0.01",
    fill = "Correlation"
  )
```


```{r}
selected_variables <-
  unbiased_data %>%
  select(language_spanish, education_bachelors_degree,
             birthplace_us, health_insurance_public, language_english,
             personal_income, employment_not_in_labor_force)
```


## Scatterplot (predictors used in the model against 2020 hosp rate)
```{r}
selected_variables <- 
  selected_variables %>%
  colnames() %>%
  as.vector() %>%
  as.list() 

for (i in selected_variables) {
  plot <-
  ggplot(unbiased_data, aes_string(i,  "puma_hosp_rate_2020")) + 
  geom_point() +
  geom_smooth(method = lm, se = FALSE) +
  labs(title = "Scatterplot", y = "2020 Hospitalization Rate") +
  theme(plot.title = element_text(hjust = 0.5, face = "bold"))
  
  print(plot) 
}
```


# 2020 Hosp Model
```{r}
best_model <- lm(puma_hosp_rate_2020  ~ language_spanish + 
                   education_bachelors_degree +
                   birthplace_us + health_insurance_public + language_english + 
                   personal_income + employment_not_in_labor_force +
                   health_insurance_public:personal_income +
                   education_bachelors_degree:employment_not_in_labor_force +
                   language_english:birthplace_us, data = unbiased_data)

full_model <-  lm(puma_hosp_rate_2020  ~ 
                    (language_spanish + education_bachelors_degree +
                     birthplace_us + health_insurance_public + language_english + 
                     personal_income + employment_not_in_labor_force)^2, 
                     data = unbiased_data)
```

## Best Model Estimates Summary
```{r}
summary(best_model) %>%
  broom::tidy()
```

## Comparing Best model vs Full model summaries 
```{r}
summary(best_model) %>% 
  broom::glance() %>%
  bind_rows(summary(full_model) %>% broom::glance()) %>%
  mutate(model = c("Best Model", "Full Model")) %>%
  relocate(model)
```

## Mallow CP
```{r}
ols_mallows_cp(best_model, full_model)
```


## Checking assumptions for linear regression
```{r}
lm_spec <- linear_reg() %>%
  set_mode("regression") %>%
  set_engine("lm")

best_model <- fit(lm_spec, puma_hosp_rate_2020  ~ language_spanish + education_bachelors_degree +
             birthplace_us + health_insurance_public + language_english + 
             personal_income + employment_not_in_labor_force +
             health_insurance_public:personal_income +
             education_bachelors_degree:employment_not_in_labor_force +
             language_english:birthplace_us,
                data = unbiased_data)

check_model(best_model, 
            check = c("qq", "normality", "linearity", 
                     "homogeneity", "outliers"))
```







